name: flutter_gif_search
description: An example Flutter application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1 # https://pub.dev/packages/cached_network_image
  cupertino_icons: ^1.0.6 # https://pub.dev/packages/cupertino_icons
  dio: ^5.4.0 # https://pub.dev/packages/dio
  enough_platform_widgets: ^1.0.0 # https://pub.dev/packages/enough_platform_widgets
  flutter: # https://docs.flutter.dev/
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^6.0.2 # https://pub.dev/packages/flutter_platform_widgets
  json_annotation: ^4.8.1 # https://pub.dev/packages/json_annotation
  logger: ^2.0.2+1 # https://pub.dev/packages/logger
  package_info_plus: ^5.0.1 # https://pub.dev/packages/package_info_plus
  retrofit: ^4.0.3 # https://pub.dev/packages/retrofit
  url_strategy: ^0.2.0 # https://pub.dev/packages/url_strategy

dev_dependencies:
  build_runner: ^2.4.7 # https://pub.dev/packages/build_runner
  flutter_lints: ^3.0.1 # https://pub.dev/packages/flutter_lints
  flutter_test: # https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html
    sdk: flutter
  json_serializable: ^6.7.1 # https://pub.dev/packages/json_serializable
  lints: ^3.0.0 # https://pub.dev/packages/lints
  retrofit_generator: ^8.0.6 # https://pub.dev/packages/retrofit_generator

flutter:
  uses-material-design: true
