name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
  JAVA_VERSION: 17

jobs:
  build:
    name: Build
    runs-on: macos-latest

    permissions:
      checks: write # For EnricoMi/publish-unit-test-result-action
      pull-requests: write # For EnricoMi/publish-unit-test-result-action
      contents: write # For peaceiris/actions-gh-pages

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.1

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2.1.1

      - name: Cache Dependencies
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
            ios/Pods
            /Users/runner/hostedtoolcache/flutter
            /Users/runner/.pub-cache
          key: ${{ runner.os }}-build
          restore-keys: |
            ${{ runner.os }}-build

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Run Build
        uses: gradle/actions/setup-gradle@v3.0.0

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: stable
          cache: true

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/unit-test-results.json

      - name: Publish Unit Test Report
        uses: EnricoMi/publish-unit-test-result-action/composite@v2.14.0
        if: always()
        with:
          check_name: "Unit Test Results"
          comment_mode: off
          files: |
            build/reports/unit-test-results.json

      - name: Build Android
        run: flutter build apk --debug

      - name: Build iOS
        run: flutter build ios --debug --no-codesign

      - name: Build Website
        run: flutter build web --base-href /flutter-gif-search/

      - name: Publish Website
        if: github.repository == 'jaredsburrows/flutter-gif-search' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: "Github Actions"
          user_email: "action@github.com"
